spring.application.name=digitalstore-backend
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_store
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

stripe.secretKey=sk_test_XXXXXXXXXXXX
stripe.webhookSecret=whsec_XXXXXXXXXXXX
stripe.currency=usd